#!/bin/bash


echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
echo "Post Deployment Include Printer & Network Setup"
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-="
sudo dpkg -i xprinter/printer-driver-xprinter_3.13.3_all.deb
sudo apt --fix-broken install
sudo systemctl status cups.service
echo "X Printer Setup is successfully installed"
chmod +x ./xprinter/XP-80
sudo ./xprinter/XP-80 
echo "sleeping ...1, 2 ,3 .."
ls -al /usr/share/cups/model/XP/
echo "Well Done For Printer Setup"
echo "."
echo "."
echo "."
echo "Please Navigate to the chromium url (localhost:631) to activate.."
echo "Socket Connection (socket://192.168.123.100:9100) for printer..."
sleep 3;
clear

# Url of socket://192.168.123.1 - 2
#### Step 8.5. Connection From LAN

#> XPrinter : 192.168.123.100

#> Computer : 192.168.123.101 . 1 (gateway)

#> socket://192.168.123.100:9100 နဲ့ cofigure လုပ်တာ အဆင်ပြေပါတယ်။ 
# Test Print 

# Debug on module 


echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo  "Static IP Lan Network For Printer"
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
nmcli device status
sudo nmcli con delete Wired\ connection\ 1
sudo nmcli con add type ethernet con-name "PrinterConn" ifname eth0 ipv4.addresses 192.168.123.101/24 ipv4.gateway "" ipv4.dns "" ipv4.method manual
sudo nmcli con up PrinterConn

echo "We need new printer setup please follow !"
sleep 2
chromium --new-tab http://localhost:631
echo "Here ! There is A new Printer ..."
echo "."
echo "."
lpstat -p
echo "."
echo "."
sleep 3

# # Printer configuration file for CUPS v2.4.10
# # Written by cupsd
# # DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING
# NextPrinterId 3
# <Printer XP>
# PrinterId 2
# UUID urn:uuid:85cd9504-e516-3dff-4eb2-e2a17170a388
# Info XP
# Location XP
# MakeModel XP-80
# DeviceURI socket://192.168.123.100
# State Idle
# StateTime 1737701237
# ConfigTime 1737701241
# Type 20484
# Accepting Yes
# Shared No
# JobSheets none none
# QuotaPeriod 0
# PageLimit 0
# KLimit 0
# OpPolicy default
# ErrorPolicy retry-job
# </Printer>



